DROP TABLE IF EXISTS ifclist;

CREATE TABLE ifclist (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  filename TEXT NOT NULL,
  state INTEGER NOT NULL
);
